config/routes.rb
KanjiDrill::Application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => 'sessions'
  }

  resources :grades, :only => [:index, :show]
  resources :checks, :only => :create

  resource :dashboard, :controller => :dashboard, :only => :show

  resource :home, :controller => :home, :only => :index
  match '/about' => 'home#about', :as => :about

  match '/s3_policy' => 'avatar#s3_policy'
  match '/fetch_avatar' => 'avatar#fetch_avatar'
  match '/poll_avatar' => 'avatar#poll'

  root :to => 'home#index'
end

app/models/check.rb
class Check < ActiveRecord::Base
  attr_accessible :result, :kanji_id, :user_id

  belongs_to :kanji
  belongs_to :user

  validates :result,
    :presence => true,
    :inclusion => { :in => [:again, :hard, :normal, :easy, 'again', 'hard', 'normal', 'easy' ] }
  validates :kanji_id, :presence => true
  validates :user_id, :presence => true

  def result=(obj)
    if obj.class == String
      result = obj.intern
    end

    super
  end
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  has_many :kanji
end

app/models/kanji.rb
class Kanji < ActiveRecord::Base
  attr_accessible :glyph, :meaning, :grade_id

  belongs_to :grade
  has_many :checks

  validates :glyph,    :presence => true
  validates :meaning,  :presence => true
  validates :grade_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :remember_me

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :encryptable,
         :encryptor => :authlogic_sha512

  has_many :checks
  has_attached_file :avatar, :styles => { :profile => "100x100>", :thumb => "30x30>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  after_filter :set_access_control_headers

  private
  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end
end

app/controllers/avatar_controller.rb
require Rails.root.join('lib', 's3_bucket_url')


class AvatarController < ApplicationController
  include S3

  def s3_policy
    render :json => {
      :policy => s3_upload_policy_document,
      :signature => s3_upload_signature,
      :key => "#{s3_key_base}/${filename}"
    }
  end

  def fetch_avatar
    current_user.avatar.destroy
    current_user.avatar.clear
    current_user.save!

    job = Jobs::ProcessAvatarJob.new(current_user, s3_url(params[:filename]))
    Delayed::Job.enqueue job

    head :ok
  end

  def poll
    if current_user.avatar.present?
      render :json => {
        thumb: current_user.avatar.url(:thumb),
        profile: current_user.avatar.url(:profile)
      }
    else
      render :json => { noop: true }
    end
  end

  private

  def s3_upload_signature
    signature = Base64.encode64(
      OpenSSL::HMAC.digest(OpenSSL::Digest::Digest.new('sha1'),
      ENV['AWS_SECRET_KEY'],
      s3_upload_policy_document)
    ).gsub("\n","")
  end

  def s3_upload_policy_document
    ret = {"expiration" => 5.minutes.from_now.utc.xmlschema,
      "conditions" =>  [
        {"bucket" =>  ENV['AWS_S3_BUCKET']},
        ["starts-with", "$key", s3_key_base],
        {"acl" => "public-read"},
        {"success_action_status" => "200"},
        ["content-length-range", 0, 5242880] # 5MB
      ]
    }

    Base64.encode64(ret.to_json).gsub(/\n/,'')
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController

  def create
    check = current_user.checks.create!(params[:check])
    stats = KanjiStats.new(current_user, check.kanji)

    render :json => stats.stats
  end
end

app/controllers/dashboard_controller.rb
require Rails.root.join('lib', 's3_bucket_url')

class DashboardController < ApplicationController
  include S3
  helper_method :s3_bucket_url

  def show
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def index

  end

  def show
    @kanji = Kanji.where(grade_id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def create
    resource = warden.authenticate(:scope => resource_name)
    if resource.present?
      sign_in(resource_name, resource)
      set_flash_message :notice, :signed_in
      render :json => { :success => true, :redirect_path => dashboard_path }
    else
      render :json => { :success => false }
    end
  end

  def new
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<%= content_for :styles do %>
  <%= stylesheet_link_tag 'dashboard' %>
<% end %>

<%= content_for :scripts do %>
  <%= javascript_include_tag 'views/dashboard/show' %>
<% end %>

<h2>Welcome!</h2>
<%= image_tag current_user.avatar.url(:profile), :alt => 'avatar', :class => 'avatar profile' %>

<form id="avatar_upload" action="<%= s3_bucket_url %>" method="POST" enctype="multipart/form-data" data-bucket="<%= ENV['AWS_S3_BUCKET'] %>">
  <button class="btn btn-success fileinput-button">
    <input type="file" name="file">
    Choose Avatar
  </button>

  <input type="hidden" name="AWSAccessKeyId" value="<%= ENV['AWS_ACCESS_KEY'] %>">
  <input type="hidden" name="acl" value="public-read">
  <input type="hidden" name="success_action_status" value="200">
  <input type="hidden" name="policy">
  <input type="hidden" name="signature">
  <input type="hidden" name="key">
</form>

<p>
  Its a little sparse in here at the moment, but expect some cool graphs to track your progress soon.
</p>

app/views/grades/index.html.erb
Please select a grade:

app/views/grades/show.html.erb
<%= content_for :styles do %>
  <%= stylesheet_link_tag 'quiz' %>
<% end %>

<%= content_for :scripts do %>
  <%= javascript_include_tag 'views/grades/show' %>
<% end %>

<script id="bootstrapKanji", type="text/json">
  <%= @kanji.to_json.html_safe %>
</script>
<div class='row'>
  <div id="quiz">
    <div class="flashcard">
      <div class="glyph"></div>
      <div class="meaning"></div>
      <div class="stats"></div>
    </div>
    <div class="btn-grp"></div>
  </div>
</div>

app/views/home/about.html.erb
<h2>About</h2>
<p>
This app helps you to remember the
<a href="http://en.wikipedia.org/wiki/Ky%C5%8Diku_kanji">
  Kyoiku Kanji
</a>
.

<h3>Instructions</h3>
<ol>
  <li>
    First, you need to make an account so your progress can be tracked. Go to
    <%= link_to "the homepage", root_path %>
    and click sign up.
  </li>
  <li>
    Next, you will be taken to your
    <%= link_to "user dashboard", dashboard_path %>
    .
    There isn't much to do here yet, but you can upload an avatar for yourself.
    Just click on the "choose avatar" button.
  </li>
  <li>
    Finally, the main event, drilling Kanji.
    Click on any of the grades at the top of the page, and begin drilling!
    The process works like this:
      <ul>
        <li>You are shown a Kanji</li>
        <li>You try and remember the meaning</li>
        <li>When you are ready, show the meaning</li>
        <li>Choose how easy or hard it was to remember</li>
        <li>The system will remember your answer and show you your progress</li>
      </ul>
  </li>
</ol>

<h4>How it works</h4>
At the moment, you will be shown Kanji at random from a given grade level.
however, soon I will be implementing a Spaced Repetition algorithm so you
will be shown kanji that you have a hard time remembering more frequently.

app/views/home/index.html.erb
<%= content_for :scripts do %>
  <%= javascript_include_tag 'login' %>
<% end %>

<div class="row-fluid">
  <div class="span6">
    <div class="hero-unit">
      <h1>漢字Drill</h1>
      <p>A fun and easy way to memorize the Kyoiku Kanji</p>
      <p>
        <%= link_to "Sign Up", new_registration_path(User), :class => ['btn', 'btn-primary', 'btn-large'] %>
        <%= link_to "Learn More", about_path, :class => ['btn', 'btn-primary', 'btn-large'] %>
      </p>
    </div>
  </div>
  <div class="span4">
    <% unless user_signed_in? %>
      <%= form_for(User.new, :url => session_path(User), :html => { :id => 'sign_in', :class => ['well', 'form-inline'] }, :remote => true, :format => :json) do |f| %>
        <div class="row-fluid">
          <%= f.email_field :email, :class => 'input-small', :placeholder => 'email' %>
          <%= f.password_field :password, :class => 'input-small', :placeholder => 'password'  %>
          <%= f.submit "Sign in", :class => 'btn btn-small' %>
        </div>
        <div class="row-fluid">
          <%= f.label :remember_me, :class => 'checkbox' do %>
            <%= f.check_box :remember_me %> Remember me
          <% end %>

          <%= link_to "Forgot your password?", new_password_path(User), :class => 'pull-right' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "KanjiDrill" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield(:styles) %>

    <link href="/favicon.ico" rel="shortcut icon">
    <link href="/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <a class="brand" href="/">Kanji Drill</a>

          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li>
                  <%= image_tag current_user.avatar.url(:thumb), :alt => 'avatar', :class => 'avatar thumb' %>
                  <%= link_to current_user.email, dashboard_path, :class => 'email' %>
                </li>
                <li>
                  <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
                </li>
              <% end %>
            </ul>
            <ul class="nav">
              <li><%= link_to "About", about_path %></li>
              <% if user_signed_in? %>
                <% Grade.all.each do |grade| %>
                  <li><%= link_to "Grade #{grade.id}", grade %></li>
                <% end %>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <%= render 'shared/flash_messages' %>
        <%= yield %>
      </div><!--/content-->

      <footer>
        <p>&copy; John Foley 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield(:scripts) %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<div id="flash">
  <% if flash[:message].present? %>
    <div class='alert alert-success'>
      <%= flash[:message] %>
    </div>
  <% end %>
  <% if flash[:notice].present? %>
    <div class='alert alert-info'>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:warning].present? %>
    <div class='alert alert-error'>
      <%= flash[:warning] %>
    </div>
  <% end %>
</div>